### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Flogis** [pvutov/WargameModManager#3]
Experiencing this error when launching the Mod Manager:
![](https://media.discordapp.net/attachments/465549200860381184/792615026724306954/Capture1.PNG)

Half the time leads to bluescreen.

**Comment by pvutov** [comment]
In your mod manager folder, there should be a file called 'settings.ini'. It should contain a line like:

`dir:H:\SteamLibrary\steamapps\common\Wargame Red Dragon`

Where `H:\SteamLibrary\steamapps\common\Wargame Red Dragon` points to a real folder that contains your game installation. Is that path correct in your version of the file?

Also, what mod are you using the mod manager with?

**Comment by Flogis** [comment]
The path in settings.ini was correct. After reviewing previous cases, I suspect this error happens when the mod manager folder is directly put on the desktop. I am waiting to see if that fixes his issue.

I was asking on behalf of someone else who isn't replying back.   Mod used is 1991 btw, I don't know if that changes anything.

Thanks for your reply !

**Comment by pvutov** [comment]
No, I was just curious. Glad to see mods other than faust's using the tool.
